### ISSUE TITLE
Series - poster

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#24]
Shows only the poster you attached to the series. 
If you have 4 episodes with different posters for each episode, the app only show the main poster added when you created the series. So only one post shows on all 4 episodes

**Comment by randheerNST** [comment]
Hi @samdudu1 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks

**Comment by samdudu1** [comment]
The feature is not in your current v1.6.9 
Series still not auto arranged "top added" - this should be the default. Which makes latest movies / last added media items show 1st. 
Currently, the latest movies / items are last on the list. Imagine have movies and series from 2016 to 2018. The new movies added 2018 shows bottom of the page. When customers click to open "series" or "movies" the old items 2016 shows up 1st. They would just assume that the site or app has very old movies
